### ISSUE TITLE
error: _fmt.substring is not a function

### ISSUE THREAD

**Issue by Modarresi** [alexei/sprintf.js#154]
I receive this error when run my program:

`TypeError: _fmt.substring is not a function
    at sprintf_parse (......\node_modules\sprintf-js\src\sprintf.js:191:25)
    at sprintf (......\node_modules\sprintf-js\src\sprintf.js:26:31)`

what is problem

**Comment by Modarresi** [comment]
ops! this is my bad use of sprintf.
sorry
my problem resolved.
