### ISSUE TITLE
gulp jobs test, dist & default fail on node v13

### ISSUE THREAD

**Issue by ashwalk33r** [alexei/sprintf.js#191]
`gulp test` throws
`assert.js:386
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/mnt/c/Users/box/Desktop/untitled/repo/sprintf.js/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/mnt/c/Users/box/Desktop/untitled/repo/sprintf.js/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/mnt/c/Users/box/Desktop/untitled/repo/sprintf.js/gulpfile.js:27:6)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at execute (/usr/local/lib/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
`

Readme mentions 
> sprintf-js runs in all active Node versions (4.x+).

On node 13 sequential gulp tasks definition throw on any gulp job run due to jobs being defined in gulp 3 way where the package.json specifies gulp 4 as dependency

tasks preventing gulp runs are:
- test
- dist
- defautl

details how to fix
https://www.liquidlight.co.uk/blog/how-do-i-update-to-gulp-4/

example:
bad
`gulp.task('test', ['lint'], function() {`

ok
`gulp.task('test', gulp.series('lint', function() {`

**Comment by alexei** [comment]
I don't have time to fix it, sorry. If anyone thinks this is important, I would consider a PR that addressed this.

**Comment by ashwalk33r** [comment]
I would anticipate a confirmation that indeed it is a reproduceable bug. Fix is litellary pasted into the report (last lines).
