### ISSUE TITLE
does't work in browser

### ISSUE THREAD

**Issue by chovy** [alexei/sprintf.js#53]
```Anonymous AMD module used, but it was not included as a dependency``

**Comment by alexei** [comment]
Hello, and thanks for your feedback.

Are you loading `sprintf` with `requirejs(['sprintf'])` or are you simply including the script in your page? I'm not a AMD user myself, but I think you should be doing the former.

**Comment by chovy** [comment]
i'm not using requirejs.

**Comment by alexei** [comment]
Ok, let's try something else: what other libraries are you using and how are you using (loading) them?

**Comment by chovy** [comment]
jquery is the only other one. I'm just using a script tag to load the sprintf.js library.

**Comment by nbarnwell** [comment]
I think the problem stems from inconsistency around naming. Is it "sprintfjs" or "sprintf-js"? The file itself is called "sprintf.js", which suggests the module name (in AMD terms) should simply be "sprint".

I suggest having a bit of a consolidation of the name and things will all sort themselves out. Also the TypeScript.DefinitelyTyped package is wrongly using a module name of "script-js". It doesn't matter what is chosen, as long as everything is consistent. It would mean the file being "sprintfjs.js", in a "sprintfjs" directory, with the module called "sprintfjs" and the corresponding TypeScript definition being "sprintfjs".

**Comment by jsinmotion** [comment]
If I'm not mistaken, the current `sprintf` module is currently wrapping an old version of this library: https://www.npmjs.com/package/sprintf -> https://github.com/maritz/node-sprintf/blob/master/lib/sprintf.js

@maritz can you release the name so that this module can use `sprintf` uniformly?

**Comment by maritz** [comment]
As far as I know, not without possibly breaking these https://www.npmjs.com/browse/depended/sprintf 

Do you know of any way to make sure a transition would be easy and not break anything?

Sadly people keep using my package despite the disclaimer at the top of the readme. :-(

**Comment by jsinmotion** [comment]
@maritz as far as I can tell, you started from https://raw.githubusercontent.com/alexei/sprintf.js/554285c46b4ac59e3a88ba83c19324812e9ecd8d/src/sprintf.js and merely added the export lines in your first commit: https://github.com/maritz/node-sprintf/blob/e6cdecfe21c388d0622939cef2158182a96943b9/lib/sprintf.js .  Some of the later commits, like cloning argv, also appear in this repo git log.  So functionality wise, had you continued updating like this repo, you would probably have something similar to the sprintf-js module.  The main feature in sprintf missing from sprintf-js is the object printing.  sprintf has `%O` which deviates from the sprintf-js `%j` for functions:

```js
> require('sprintf-js').sprintf("%j", console.log)

''
> require('sprintf').sprintf("%O", console.log)
'[Function: bound ]'
```

The relevant code can be found here: https://github.com/maritz/node-sprintf/blob/master/lib/sprintf.js#L80 . That functionality has to be added to this module, as well as exposing the `object_stringify` method.

Assuming that we can put together a PR and @alexei approves, the next step could be:

A) just make sprintf a wrapper that depends on sprintf-js

OR

B) Adjust the sprintf-js api to align with the sprintf API and push the module to sprintf, making sprintf-js the wrapper.

The API difference is pretty minimal: sprintf directly exports the sprintf function whereas sprintf-js exports an object.   For example, in the (A) approach, the sprintf module would be:

```javascript
var old_sprintf = require('sprintf-js');
var sprintf = old_sprintf.sprintf;
sprintf.sprintf = sprintf;
sprintf.vsprintf = old_sprintf.vsprintf;
module.exports = sprintf;
```

**Comment by alexei** [comment]
> That functionality **has** to be added to this module
What are the use cases for it?

This module will be split into two so that it doesn't export an object anymore. That might pave the way to rename it if @maritz agrees to drop the name. But even though I'm generally reckless enough to make a package unavailable for a couple of minutes, I admit I don't know how to do it right.

**Comment by maritz** [comment]
Just to make this clear: I really don't care about the name, my fork of your project on github or my package on npm.

But I very strongly care about not breaking any other packages/projects.

I don't really understand what the problem is right now or what the proposed solutions are. Sadly I currently have very little capacity to do any work on this.

**Comment by jsinmotion** [comment]
@maritz the underlying problem is not with your implementation or the current module, it is with some third party bundlers and AMD module loaders that get confused because the main npm module name is `sprintf-js` but the source file is `sprintf.js`.  If the two modules were spiritually and functionally irreconcilable we would have to find another workaround, but since https://www.npmjs.com/package/sprintf hasn't been touched in more than 2 years and attempts to redirect people to this module, it makes sense to explore whether the two modules can be merged.

@alexei when I said that it "has" to be added, it is the only functionality present in `sprintf` that is not in `sprintf-js`, so adding that functionality is a prerequisite for a unification.

If both of you are in agreement that we should try to reduce the overall confusion surrounding both `sprintf` and `sprintf-js` modules, I think the most painless process is:

1) merge the relevant features from the sprintf module to the sprintf-js module.  I looked at the diff and the main functionality that is in sprintf but not sprintf-js is the `%O` for rendering objects.  The code block starts here https://github.com/maritz/node-sprintf/blob/master/lib/sprintf.js#L80 .  To maintain 100% backward compatibility with the existing sprintf module, the function would have to be exported as `object_stringify` as well

2) fix the modules.  There are 2 ways to do this:

A) change the `sprintf` module by making it a simple wrapper around sprintf-js.  Based on my cursory understanding of the git changes in the last few years, there were no major breaking changes that would disrupt a user.  The main difference is `sprintf` exports the sprintf function directly (like how 0.7 version of the library did it) and sprintf-js does not.  This is an easy fix.

B) change the sprintf-js library to align with the API of sprintf and then publish to sprintf directly.  Changing the source here is straightforward: export the sprintf function rather than the object that houses both, then attach sprintf and vsprintf as keys of the sprintf function.  

@maritz if all of this seems too much and you are afraid of making changes, could you at least deprecate the module using npm deprecate? https://docs.npmjs.com/cli/deprecate

**Comment by alexei** [comment]
I got the point on aligning functionality, yet I'm reluctant about adding the `object_stringify` function which seems like an opinionated way of representing objects. JSON is near & dear to any JS developer and should suffice for most if not all cases. Imho moving it into it's own project would suit it better

**Comment by jsinmotion** [comment]
@alexei right now sprintf-js does not use the `%O` conversion:

```
> require("sprintf-js").sprintf("%O",[1,2,3])
SyntaxError: [sprintf] unexpected placeholder
```

So this is not breaking existing functionality.  This can coexist with the JSON `%j` rendering.  And on a somewhat related note, the WHATWG console spec mentions %O and at first blush the object_stringify function satisfies the requirement:  https://console.spec.whatwg.org/#formatter

To answer the question about JSON deficiencies, the biggest problem is with circular structures:

```js
> var x = {}; x.x = x; x;
{ x: [Circular] } // <-- node knows it's a circular reference
> require("sprintf-js").sprintf("%j", x)
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at sprintf.format (/usr/local/lib/node_modules/sprintf-js/src/sprintf.js:73:36)
    at Object.sprintf (/usr/local/lib/node_modules/sprintf-js/src/sprintf.js:21:31)
    at repl:1:23
    at realRunInThisContextScript (vm.js:22:35)
    at sigintHandlersWrap (vm.js:98:12)
    at ContextifyScript.Script.runInThisContext (vm.js:24:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
> require("sprintf").sprintf("%O", x)
'{x: {x: {x: {x: {x: [Object]}}}}}'
```

Whether object_stringify is doing the right thing here is up for debate, but it is definitely not blowing up with an error in the same way that JSON does.  Again, not saying one is better than the other, but both can coexist since %O is not currently being used
